# BybitOutputCandle short keys
TRADE_INDEX = "ti"
ENTRY_PRICE = "ep"
STOP_LOSS = "sl"
TAKE_PROFIT = "tp"
TRADE_SIZE = "ts"
EXIT_PRICE = "xp"
PNL = "p"
IS_PROFIT = "pr"
OPEN_TIME = "t"
CLOSE_TIME = "ct"
OPEN_PRICE = "o"
CLOSE_PRICE = "c"
HIGH_PRICE = "h"
LOW_PRICE = "l"
VOLUME = "v"
QUOTE_VOLUME = "q"
